spring:
  application:
    name: random-data
  datasource:
    url: jdbc:postgresql://localhost:5432/flink
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
